### ISSUE TITLE
Fan selection

### ISSUE THREAD

**Issue by compiled-somehow** [willblev/UDS_ATC#2]
Hi mate. This looks amazing and thought I’d give it a go.

I have most of it working and ready to attach to my drum for testing/tuning. The only thing holding up the process is that I can’t manage to shut the fan off completely, which could be a large problem once on the drum. 

I have tried a bunch of duty cycle values and my fan appears to run at 100% with 0 duty cycle and slowest at 255, then faster again as it increases from there up to 1000, but at no point shuts off.

Did you happen to come across this at all?
I’m assuming now that the fan I purchased can not be shut down via pwm. Would you be able to share the model number of the fan you used in you set up please? 

Thanks for sharing your awesome project.

**Comment by willblev** [comment]
Hi! 
Glad to hear your build is going well otherwise! I did run in to the exact same problem. 4 wire fans that can be controlled via PWM have an ESC board inside them- this circuit detects the input and decides how fast the fan should go, then looks at the tachometer to see how fast it is turning. Depending on the specs of your particular fan model, if it doesn't detect an input that falls within the expected range, it may ramp up to full speed. From what I remember, my fan (a Dell KH302 harvested from an old server rack)
did the same thing. I think I got my hands on the spec sheet for this model, and found a chart that showed the relationship between input duty cycle/fan RPM.

If you're unable to dig up a specification sheet for your fan model, I can think of 2 possible solutions: 1. Use another GPIO coupled with a hefty transistor to toggle power (on/off) to the fan if you want to be sure you can really get 0 RPM. 2. Make a quick sketch that starts the fan off at 255 and increments down to 0 (printing the value to serial monitor every second) to see what the lowest possible duty cycle is for your fan before it decides to kick up to full blast. 

Best of luck and let me know if you have any other questions!

**Comment by compiled-somehow** [comment]
Thanks for your help mate. I have it all working now. Ended up with an IRL540N to switch it off completely when target and/or pull temp is reached. I did use a logic level converter to up the current as the digital pin wasn’t sufficient to saturate the gate. It’s now running as expected during testing. I will be making a box for it sometime over the next week which will use a barrel union to connect to an existing inlet, and adding an open lid function to drop the temp by x degrees before opening the lid to help limit temp spikes. Can’t wait to get this on the drum.

**Comment by willblev** [comment]
No problem! I was going to include a lid sensor to attempt to do the same thing (try to avoid temperature spikes) but in the end I prioritized finishing the project to be able to start smoking. Be sure to post your tweaks and improvements somewhere!

**Comment by compiled-somehow** [comment]
Will do mate. Cheers.
